config/routes.rb
JusthateIt::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#index'
  
  devise_for :users do
    delete 'users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  resources :authentications, :only => [:index, :create, :destroy]
  resources :hates, :only => [:index, :new, :create, :destroy]

  root :to => 'hates#index'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
  <meta name="description" content="">

  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "/fonts/neon/stylesheet.css" %>
  <%= stylesheet_link_tag "/fonts/roboto/stylesheet.css" %>  
  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  <%= yield(:head) %>  
</head>
<body>
	<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
	<div class="container">  
	  <!--
	  <div id="user_nav">
      <% if user_signed_in? %>
        <%= image_tag current_user.avatar.url(:small) %>
        Signed in as <%= current_user.name %>.<br />
        Not you? <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign In", authentications_path %>
      <% end %>
    </div>
    
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= content_tag :h1, yield(:title) if show_title? %>
  -->
  
    <div id="user_nav">
      <% if user_signed_in? %>
        <%= image_tag current_user.avatar.url(:small) %>
        Signed in as <%= current_user.name %> (<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>).
      <% else %>
        <%= link_to "Sign In", authentications_path %>
      <% end %>
    </div>
	  
		<header>
			Start hating with us
		</header>
		<div role="main">

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
		  
      <%= yield %>		  
		</div>
		<footer>
      Created by Vad Vlad and Steve in 2012
		</footer>
	</div>

</body>
</html>